# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Mar 21 00:57:56 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ConnectionDialogTemplate(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ConnectionDialogTemplate.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Establish Connection")

        self.sizer = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Select Driver")
        self.sizer.Add(label_1, 0, 0, 0)

        self.driver_selection = wx.Choice(self, wx.ID_ANY, choices=[])
        self.sizer.Add(self.driver_selection, 0, 0, 0)

        self.parameters_panel = wx.Panel(self, wx.ID_ANY)
        self.sizer.Add(self.parameters_panel, 1, wx.EXPAND, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        self.sizer.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(self.sizer)
        self.sizer.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        # end wxGlade

# end of class ConnectionDialogTemplate
