# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Sun Apr  2 16:16:58 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LccNodesViewerTemplate(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LccNodesViewerTemplate.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((731, 607))
        self.SetTitle("LCC Nodes")

        self.splitter = wx.SplitterWindow(self, wx.ID_ANY)
        self.splitter.SetMinimumPaneSize(20)

        self.node_select_panel = wx.Panel(self.splitter, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.node_select_panel, wx.ID_ANY, "Select a node")
        sizer_1.Add(label_1, 0, 0, 0)

        self.node_list = wx.ListCtrl(self.node_select_panel, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.node_list.AppendColumn("Name", format=wx.LIST_FORMAT_LEFT, width=200)
        self.node_list.AppendColumn("ID", format=wx.LIST_FORMAT_LEFT, width=150)
        sizer_1.Add(self.node_list, 1, wx.EXPAND, 0)

        self.node_detail_panel = wx.Panel(self.splitter, wx.ID_ANY)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.notebook = wx.Notebook(self.node_detail_panel, wx.ID_ANY)
        sizer_2.Add(self.notebook, 1, wx.EXPAND, 0)

        self.notebook_node_info = wx.Panel(self.notebook, wx.ID_ANY)
        self.notebook.AddPage(self.notebook_node_info, "Node Info")

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.node_info_text = wx.TextCtrl(self.notebook_node_info, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        sizer_3.Add(self.node_info_text, 1, wx.EXPAND, 0)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 0, wx.ALIGN_RIGHT, 0)

        self.button_refresh = wx.Button(self.node_detail_panel, wx.ID_ANY, "Refresh all fields")
        sizer_5.Add(self.button_refresh, 0, wx.ALL, 5)

        self.notebook_node_info.SetSizer(sizer_3)

        self.node_detail_panel.SetSizer(sizer_2)

        self.node_select_panel.SetSizer(sizer_1)

        self.splitter.SplitVertically(self.node_select_panel, self.node_detail_panel, 350)

        self.Layout()
        # end wxGlade

# end of class LccNodesViewerTemplate
