# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Sun Mar 26 21:28:39 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SettingsDialogTemplate(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SettingsDialogTemplate.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("LCC Browser Settings")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        sizer_1.Add(self.panel_1, 1, wx.ALL | wx.EXPAND, 5)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Node ID")
        sizer_4.Add(label_3, 0, wx.TOP, 0)

        self.node_id = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_4.Add(self.node_id, 0, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "HTML file for layout display")
        sizer_4.Add(label_4, 0, wx.TOP, 10)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_5, 0, wx.EXPAND, 0)

        self.choose_html_path = wx.Button(self.panel_1, wx.ID_ANY, "Choose...")
        sizer_5.Add(self.choose_html_path, 0, 0, 0)

        self.html_path = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_5.Add(self.html_path, 1, wx.EXPAND | wx.LEFT, 5)

        self.auto_connect = wx.CheckBox(self.panel_1, wx.ID_ANY, "Auto connect CAN bus on program start")
        sizer_4.Add(self.auto_connect, 0, wx.TOP, 10)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 5)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.panel_1.SetSizer(sizer_4)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.on_choose_html_path, self.choose_html_path)
        # end wxGlade

    def on_choose_html_path(self, event):  # wxGlade: SettingsDialogTemplate.<event_handler>
        print("Event handler 'on_choose_html_path' not implemented!")
        event.Skip()

# end of class SettingsDialogTemplate
